# Generated by Django 4.1.3 on 2022-12-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_tour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.DateField(),
        ),
    ]
