# Generated by Django 4.1.4 on 2022-12-16 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_delete_sale_alter_tour_breaker_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
