# Generated by Django 4.1.3 on 2022-12-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_tour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='ups_BL05ID_load',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_PPOZ_load',
            field=models.IntegerField(default=0),
        ),
    ]
