# Generated by Django 4.1.3 on 2022-12-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_alter_tour_ups_bl04bm_l1_alter_tour_ups_bl04bm_l2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='ups_BL04BM_battery_voltages',
            field=models.IntegerField(default=272),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL04ID_battery_voltages',
            field=models.IntegerField(default=272),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL05ID_battery_voltages',
            field=models.IntegerField(default=242),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL06ID_battery_voltages',
            field=models.IntegerField(default=272),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL09BM_battery_voltages',
            field=models.IntegerField(default=272),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL10BM_battery_voltages',
            field=models.IntegerField(default=272),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_GPD_battery_voltages',
            field=models.IntegerField(default=272),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_PPOZ_battery_voltages',
            field=models.IntegerField(default=242),
        ),
    ]
