# Generated by Django 4.1.3 on 2022-12-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_alter_tour_ups_bl04bm_battery_voltages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='bat11_weekly_TPF',
            field=models.CharField(default=0.99, max_length=300),
        ),
        migrations.AlterField(
            model_name='tour',
            name='bat12_weekly_TPF',
            field=models.CharField(default=0.99, max_length=300),
        ),
        migrations.AlterField(
            model_name='tour',
            name='bat21_weekly_TPF',
            field=models.CharField(default=0.99, max_length=300),
        ),
        migrations.AlterField(
            model_name='tour',
            name='bat31_weekly_TPF',
            field=models.CharField(default=0.99, max_length=300),
        ),
    ]
