# Generated by Django 4.1.3 on 2022-12-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_alter_tour_bat11_weekly_tpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='failures',
            field=models.CharField(default='Brak', max_length=300),
        ),
    ]
