# Generated by Django 4.1.4 on 2022-12-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_alter_tour_failures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='lamp_status',
            field=models.CharField(default='Zielone', max_length=300),
        ),
    ]
