# Generated by Django 4.1.4 on 2022-12-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_alter_tour_lamp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='lamp_status',
            field=models.CharField(choices=[('Zielone', 'Zielone'), ('Czerwone', 'Czerwone')], default='Zielone', max_length=300),
        ),
    ]
