# Generated by Django 4.1.4 on 2022-12-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_alter_tour_lamp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='sn_field_3_v12',
            field=models.FloatField(default=15.55),
        ),
        migrations.AlterField(
            model_name='tour',
            name='sn_field_3_v23',
            field=models.FloatField(default=15.55),
        ),
        migrations.AlterField(
            model_name='tour',
            name='sn_field_3_v31',
            field=models.FloatField(default=15.55),
        ),
        migrations.AlterField(
            model_name='tour',
            name='sn_field_5_v12',
            field=models.FloatField(default=15.55),
        ),
        migrations.AlterField(
            model_name='tour',
            name='sn_field_5_v23',
            field=models.FloatField(default=15.55),
        ),
        migrations.AlterField(
            model_name='tour',
            name='sn_field_5_v31',
            field=models.FloatField(default=15.55),
        ),
    ]
