# Generated by Django 4.1.4 on 2022-12-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_alter_tour_sn_field_3_v12_alter_tour_sn_field_3_v23_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='ups_BL04BM_failures',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL04ID_failures',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL05ID_failures',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL06ID_failures',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL09BM_failures',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_BL10BM_failures',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_GPD_failures',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='ups_PPOZ_failures',
            field=models.CharField(default='brak', max_length=100),
        ),
    ]
