# Generated by Django 4.1.4 on 2023-01-21 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0017_alter_tour_bswok_charger_alter_tour_mains_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='supply_tor_1',
            new_name='rozdz_rge_ac_supply_tor_1',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='supply_tor_2',
            new_name='rozdz_rge_ac_supply_tor_2',
        ),
    ]
