# Generated by Django 4.1.4 on 2023-01-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_rename_supply_tor_1_tour_rozdz_rge_ac_supply_tor_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='ups_1_34_failures',
            field=models.CharField(default='brak', max_length=100),
        ),
    ]
